name: minechat
version: '1.0-SNAPSHOT'
main: me.harshit.minechat.Minechat
api-version: '1.20'
description:  Chat plugin with MongoDB integration, web interface, friend system, and chat groups
author: Harshit

commands:
  minechat:
    description: Main MineChat command for web password management
    usage: /minechat <setpassword|removepassword|status|reload>
    aliases: [mc, mchat]
  msg:
    description: Send a private message to a player
    usage: /msg <player> <message>
    aliases: [message]
  pm:
    description: Send a private message to a player
    usage: /pm <player> <message>
  tell:
    description: Send a private message to a player
    usage: /tell <player> <message>
  whisper:
    description: Send a private message to a player
    usage: /whisper <player> <message>
    aliases: [w]
  reply:
    description: Reply to the last private message received
    usage: /reply <message>
    aliases: [r]
  friend:
    description: Friend system commands
    usage: /friend <add|accept|deny|remove|list|requests>
    aliases: [friends, f]
  group:
    description: Chat groups commands
    usage: /group <create|invite|accept|deny|leave|list|chat|info>
    aliases: [groups, g]

permissions:
  minechat.admin:
    description: Admin permissions for MineChat
    default: op
  minechat.use:
    description: Basic usage permissions for MineChat
    default: true
  minechat.web:
    description: Permission to set web passwords
    default: true
  minechat.pm:
    description: Permission to send private messages
    default: true
  minechat.friends:
    description: Permission to use friend system
    default: true
  minechat.friends.add:
    description: Permission to send friend requests
    default: true
  minechat.friends.unlimited:
    description: Bypass friend limits (for VIP players)
    default: op
  minechat.groups:
    description: Permission to use group system
    default: true
  minechat.groups.create:
    description: Permission to create groups
    default: true
  minechat.groups.unlimited:
    description: Bypass group limits (for VIP players)
    default: op
